services:
  auth-service:
    image: spring-security-oauth-hands-on:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-security-oauth-hands-on
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS_HOST:-host.docker.internal}
      REDIS_PORT: 6379
    restart: unless-stopped

  redis-stack:
    image: redis/redis-stack:latest
    profiles:
      - with-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
